### ISSUE TITLE
Option to remove squared background?

### ISSUE THREAD

**Issue by taxilly** [tmthrgd/ditaa-ditaa#2]
Is it possible to incorporate an option to disable the squared background? So that the background is just white or transparent.
Here's a picture of what I mean by squared background, the grey lines in the background.
http://movw-space.cf/f/bfbk47.png

**Comment by tmthrgd** [comment]
That option already exists, (from the ditaa documentation):

>  -d,--debug                 Renders the debug grid over the resulting image.

Removing the debug option will fix that - you can use verbose if you still want more information about the rendering.

**Comment by taxilly** [comment]
Ah right,  I meant to use verbose, missed that one, thanks.
